rework

diff --git a/charts/open-webui/charts/tika/.github/workflows/lint-test.yaml b/charts/open-webui/charts/tika/.github/workflows/lint-test.yaml
--- a/charts/open-webui/charts/tika/.github/workflows/lint-test.yaml
+++ b/charts/open-webui/charts/tika/.github/workflows/lint-test.yaml
@@ -27,23 +27,17 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4.1.5
         with:
           fetch-depth: 0
-
       - name: Set up Helm
-        uses: azure/setup-helm@v3
+        uses: azure/setup-helm@v4.2.0
+      - uses: actions/setup-python@v5.1.0
         with:
-          version: v3.10.0
-
-      - uses: actions/setup-python@v4
-        with:
-          python-version: '3.9'
+          python-version: '3.x'
           check-latest: true
-
       - name: Set up chart-testing
-        uses: helm/chart-testing-action@v2.3.1
-
+        uses: helm/chart-testing-action@v2.6.1
       - name: Run chart-testing (list-changed)
         id: list-changed
         run: |
@@ -51,14 +45,39 @@ jobs:
           if [[ -n "$changed" ]]; then
             echo "::set-output name=changed::true"
           fi
-
+        shell: bash
       - name: Run chart-testing (lint)
         run: ct lint --target-branch ${{ github.event.repository.default_branch }} --charts .
-
+        shell: bash
       - name: Create kind cluster
-        uses: helm/kind-action@v1.4.0
+        uses: helm/kind-action@v1.10.0
         if: steps.list-changed.outputs.changed == 'true'
-
+      - name: Uninstall helm-unittest if present
+        run: |
+          helm plugin uninstall unittest >/dev/null 2>/dev/null \
+            || echo "Failed to uninstall plugin, assuming it's not present."
+        shell: bash
+      - name: Install latest helm-unittest
+        run: |
+          echo "Installing latest version of helm-unittest"
+          helm plugin install https://github.com/helm-unittest/helm-unittest >/dev/null 2>/dev/null
+        shell: bash
+      - name: Assemble list of chart directories to test
+        run: |
+          tr ' ' '\n' <<< . | grep -v '^$' > charts-to-test || true
+          find . -type f -name 'Chart.yaml' -exec dirname {} \; > all-charts
+          [ -z . ] && mv all-charts charts-to-test || true
+        shell: bash
+      - name: Fetch chart dependencies
+        run: |
+          for chart in $(cat charts-to-test); do
+            helm dependency update "$chart" >/dev/null
+          done
+        shell: bash
+      - name: Run unit tests
+        run: helm unittest --color $(cat charts-to-test)
+        shell: bash
       - name: Run chart-testing (install)
-        run: ct install --target-branch ${{ github.event.repository.default_branch }} --charts .
         if: steps.list-changed.outputs.changed == 'true'
+        run: ct install --target-branch ${{ github.event.repository.default_branch }} --charts .
+        shell: bash
